### PR TITLE
Add new area codes.

### PR DESCRIPTION
**Pull request by jtwhittington**
Added new area codes according to [here](http://www.lincmad.com/areacode.html). We were going to just update the ones that aren't yet active but soon will be. Maybe you want to do separate versions for the future area codes?

### CODE REVIEW

**Comment by amedeiros** [comment]
Are these area codes replacing other area codes or are they in addition to?

**Comment by jtwhittington** [comment]
They are in addition to, new overlays - multiple area codes for same geographic area.

**Comment by amedeiros** [comment]
:+1:

**Comment by amedeiros** [comment]
@jtwhittington The new version 0.0.5 is in ruby gems.

**Comment by jtwhittington** [comment]
Thanks!

**Pull request merged**
